name: cryptoenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - requests
  - dataclasses
  - pandas
  - matplotlib==3.2.2
  - numpy
  - pytrends
  - mplfinance
  - python-telegram-bot
  - python-dateutil
  - pytest
  - pytest-cov
  - pip
  - pip:
    - trendln
    - pandas-ta
    - git+https://github.com/giocaizzi/cryptoCMD.git
    - bob-telegram-tools
    - coinbase
