name: "Documentation"

on:
  push:
    branches:
      - gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Test building docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docsrc/"
        build-command : make html

    # - name: Build Sphinx Doccs
    #   uses: ammaraskar/sphinx-action@master
    #   with:
    #     docs-folder: "docsrc/"
    #     build-command : make github

    # - name: Commit documentation changes
    #   run: |
    #     git clone https://github.com/giocaizzi/surfingcrypto.git --branch gh-pages --single-branch gh-pages
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git commit -m "Update documentation" -a || true
    #     # The above command will fail if no changes were present, so we ignore
    #     # the return code.
  
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: gh-pages
    #     directory: gh-pages
    #     github_token: ${{ secrets.GITHUB_TOKEN }}